-- auto Generated on 2018-01-19 14:29:29 
-- DROP TABLE IF EXISTS car; 
CREATE TABLE car(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	volum DOUBLE (16,4) NOT NULL DEFAULT -1.0 COMMENT 'volum',
	name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	tele BIGINT (15) NOT NULL DEFAULT -1 COMMENT 'tele',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'car';
